name: deploy branch (pre-prod)
on:
  workflow_dispatch:
    inputs: {}
  release:
    types: [published]

jobs:
  setup-build-publish-deploy:
    name: deploy pre-prod
    runs-on: ubuntu-latest

    steps:
      - name: log
        run: |
          echo "deployed"
